// Postgres provisioning helper invoked by `friday setup` (ADR-023).
//
// Idempotent: safe to run any number of times. Each step is guarded by an
// existence check or a CATCH on the duplicate-object error class.
//
// Responsibilities:
//   1. Verify Postgres is reachable (pg_isready).
//   2. Generate `friday` role + database if missing.
//   3. Persist `DATABASE_URL` to ~/.friday/.env.
//   4. Apply Drizzle Postgres migrations from packages/shared/drizzle-pg/.
//   5. Apply FTS_SETUP_SQL (generated tsvector columns + GIN indexes).
//   6. Create publication `friday_pub` for Zero's logical replication.
//
// Phase 0 caveat: this runs side-by-side with the legacy SQLite migration
// chain. The daemon code path still reads/writes SQLite; Postgres exists
// but is unused at runtime until Phase 1.

import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import pgPkg from "pg";
import { ZERO_DIR } from "../config.js";
import { upsertEnvVar } from "../env.js";
import { FTS_SETUP_SQL } from "./schema.js";

const { Client } = pgPkg;

const FRIDAY_DB = "friday";
const FRIDAY_ROLE = "friday";
const FRIDAY_PUBLICATION = "friday_pub";

export interface ProvisionResult {
  /** True when this run created a brand-new role/database/migration chain. */
  freshInstall: boolean;
  /** DATABASE_URL written to ~/.friday/.env. */
  databaseUrl: string;
  /** Migrations applied this run. Empty when already at head. */
  appliedMigrations: string[];
  /** True when the publication was created this run. */
  createdPublication: boolean;
}

/**
 * Run the full provisioning pipeline. Idempotent. Throws on unrecoverable
 * errors (Postgres unreachable, permission denied at the admin layer, etc.)
 * with an actionable message.
 */
export async function provisionPostgres(opts: {
  /** Override the migration directory (defaults to the shared package's). */
  migrationsDir?: string;
  /** Caller for logging — `setup` prints, tests stay quiet. */
  log?: (msg: string) => void;
}): Promise<ProvisionResult> {
  const log = opts.log ?? (() => {});
  const migrationsDir = opts.migrationsDir ?? defaultMigrationsDir();

  assertPgReady();
  log("  postgres is reachable");

  const adminUrl = adminConnectionUrl();
  const password = generateOrReuseFridayPassword();
  const created = await ensureRoleAndDatabase(adminUrl, password, log);

  const databaseUrl = `postgresql://${FRIDAY_ROLE}:${encodeURIComponent(
    password,
  )}@localhost:5432/${FRIDAY_DB}`;
  upsertEnvVar("DATABASE_URL", databaseUrl);
  log(`  DATABASE_URL → ~/.friday/.env`);

  // Phase 2 / ADR-024: zero-cache reads ZERO_UPSTREAM_DB (the Postgres URL
  // it replicates from) and ZERO_REPLICA_FILE (its internal sqlite cache).
  // Mirror the Postgres URL here so a single `friday setup` flow puts
  // both DATABASE_URL and ZERO_UPSTREAM_DB in `.env` — keeping them in sync
  // when the password is rotated.
  upsertEnvVar("ZERO_UPSTREAM_DB", databaseUrl);
  const zeroReplicaFile = join(ZERO_DIR, "replica.db");
  if (!existsSync(ZERO_DIR)) mkdirSync(ZERO_DIR, { recursive: true });
  upsertEnvVar("ZERO_REPLICA_FILE", zeroReplicaFile);
  // Point zero-cache at the existing `friday_pub` publication (created
  // here in `ensurePublication` via admin connection — friday role
  // doesn't have superuser, so we can't let zero-cache CREATE
  // PUBLICATION on its own). The option lives under Zero's `app`
  // options, so the env name is ZERO_APP_PUBLICATIONS (not
  // ZERO_UPSTREAM_PUBLICATIONS, which doesn't exist).
  upsertEnvVar("ZERO_APP_PUBLICATIONS", FRIDAY_PUBLICATION);
  log(
    `  ZERO_UPSTREAM_DB + ZERO_REPLICA_FILE + ZERO_UPSTREAM_PUBLICATIONS → ~/.friday/.env`,
  );

  // ZERO_AUTH_SECRET is generated by ensureFridayEnv() (called by `friday
  // setup` before provisionPostgres). Verify it's present so we fail loudly
  // if a future caller skips that step.
  if (!process.env.ZERO_AUTH_SECRET) {
    throw new Error(
      "ZERO_AUTH_SECRET not set. Call ensureFridayEnv() before provisionPostgres().",
    );
  }

  const appliedMigrations = await applyMigrations(
    databaseUrl,
    migrationsDir,
    log,
  );

  const createdPublication = await ensurePublication(databaseUrl, log);

  // Phase 2 (ADR-024): Zero needs logical replication enabled. The
  // default `wal_level = replica` leaves zero-cache in a boot loop —
  // surface the fix here so `friday setup` is idempotent end-to-end.
  await ensureWalLevelLogical(log);

  return {
    freshInstall: created.role || created.database,
    databaseUrl,
    appliedMigrations,
    createdPublication,
  };
}

/* -------------------- helpers -------------------- */

function defaultMigrationsDir(): string {
  // Resolve relative to this file's location. Post-build path is
  // `dist/db/pg-provision.js`; source-tree path is `src/db/pg-provision.ts`.
  // In both cases, going up two levels reaches the package root where
  // `drizzle/` lives (the canonical Postgres migration dir after the
  // Phase 1 swap).
  const here = new URL("..", import.meta.url).pathname;
  const pkgRoot = join(here, "..");
  return join(pkgRoot, "drizzle");
}

function assertPgReady(): void {
  const result = spawnSync("pg_isready", { encoding: "utf8" });
  if (result.status !== 0) {
    throw new Error(
      `Postgres is not reachable. Run \`brew services start postgresql@18\` and re-run setup.\n` +
        `  pg_isready exit=${result.status} stdout=${result.stdout?.trim()} stderr=${result.stderr?.trim()}`,
    );
  }
}

function adminConnectionUrl(): string {
  // Connect as the current OS user to the default 'postgres' database to
  // perform role/database creation. On macOS Homebrew Postgres, the
  // current OS user is the superuser by default.
  const user = process.env.USER ?? "postgres";
  return `postgresql://${user}@localhost:5432/postgres`;
}

function generateOrReuseFridayPassword(): string {
  const existing = process.env.DATABASE_URL;
  if (existing) {
    try {
      const url = new URL(existing);
      if (url.password) return decodeURIComponent(url.password);
    } catch {
      // Malformed URL — fall through to generation.
    }
  }
  return randomBytes(24).toString("base64url");
}

async function ensureRoleAndDatabase(
  adminUrl: string,
  password: string,
  log: (msg: string) => void,
): Promise<{ role: boolean; database: boolean }> {
  const client = new Client({ connectionString: adminUrl });
  await client.connect();
  try {
    let createdRole = false;
    let createdDatabase = false;

    const roleExists = await client.query(
      `SELECT 1 FROM pg_roles WHERE rolname = $1`,
      [FRIDAY_ROLE],
    );
    if (roleExists.rows.length === 0) {
      // Password is parameterized via crypto-safe escape (single-quote
      // escaping); Postgres doesn't accept bind parameters in CREATE ROLE.
      // REPLICATION grants the role permission to use logical replication
      // (required by zero-cache); LOGIN lets the role authenticate normally.
      const escapedPwd = password.replace(/'/g, "''");
      await client.query(
        `CREATE ROLE ${FRIDAY_ROLE} LOGIN REPLICATION PASSWORD '${escapedPwd}'`,
      );
      createdRole = true;
      log(`  created role ${FRIDAY_ROLE} (LOGIN REPLICATION)`);
    } else {
      // Update the password + ensure REPLICATION attribute. Idempotent.
      const escapedPwd = password.replace(/'/g, "''");
      await client.query(
        `ALTER ROLE ${FRIDAY_ROLE} WITH LOGIN REPLICATION PASSWORD '${escapedPwd}'`,
      );
      log(`  role ${FRIDAY_ROLE} already exists (password + REPLICATION synced)`);
    }

    const dbExists = await client.query(
      `SELECT 1 FROM pg_database WHERE datname = $1`,
      [FRIDAY_DB],
    );
    if (dbExists.rows.length === 0) {
      await client.query(`CREATE DATABASE ${FRIDAY_DB} OWNER ${FRIDAY_ROLE}`);
      createdDatabase = true;
      log(`  created database ${FRIDAY_DB}`);
    } else {
      log(`  database ${FRIDAY_DB} already exists`);
    }

    return { role: createdRole, database: createdDatabase };
  } finally {
    await client.end();
  }
}

interface JournalEntry {
  idx: number;
  version: string;
  when: number;
  tag: string;
  breakpoints: boolean;
}

interface Journal {
  version: string;
  dialect: string;
  entries: JournalEntry[];
}

async function applyMigrations(
  databaseUrl: string,
  migrationsDir: string,
  log: (msg: string) => void,
): Promise<string[]> {
  const journalPath = join(migrationsDir, "meta", "_journal.json");
  if (!existsSync(journalPath)) {
    throw new Error(
      `Migration journal not found at ${journalPath}. ` +
        `Did you run \`pnpm --filter @friday/shared exec drizzle-kit generate --config=drizzle.config.pg.ts\`?`,
    );
  }
  const journal = JSON.parse(readFileSync(journalPath, "utf8")) as Journal;

  const client = new Client({ connectionString: databaseUrl });
  await client.connect();
  const applied: string[] = [];
  try {
    // Drizzle's Postgres migrator tracks applied migrations in
    // drizzle.__drizzle_migrations (separate schema to avoid colliding
    // with app tables). Create it if missing and use it as the cursor.
    await client.query(`CREATE SCHEMA IF NOT EXISTS drizzle`);
    await client.query(`
      CREATE TABLE IF NOT EXISTS drizzle.__drizzle_migrations (
        id SERIAL PRIMARY KEY,
        hash TEXT NOT NULL,
        created_at BIGINT
      )
    `);

    const appliedRows = await client.query<{ created_at: string }>(
      `SELECT created_at FROM drizzle.__drizzle_migrations`,
    );
    const appliedWhens = new Set(
      appliedRows.rows.map((r) => Number(r.created_at)),
    );

    // Acquire advisory lock so concurrent setup invocations (or daemon
    // boot vs. setup) can't race the migration application. The lock
    // key 0x4652494441590001 is "FRIDAY\x00\x01" as bigint — distinct,
    // namespaced, no collision risk.
    const LOCK_KEY = BigInt("0x4652494441590001");
    await client.query(`SELECT pg_advisory_lock($1)`, [LOCK_KEY.toString()]);
    try {
      const sortedEntries = [...journal.entries].sort(
        (a, b) => a.when - b.when,
      );
      for (const entry of sortedEntries) {
        if (appliedWhens.has(entry.when)) continue;
        const sqlPath = join(migrationsDir, `${entry.tag}.sql`);
        if (!existsSync(sqlPath)) {
          throw new Error(
            `Migration file missing: ${sqlPath} (referenced by journal)`,
          );
        }
        const rawSql = readFileSync(sqlPath, "utf8");
        // Split on the drizzle statement-breakpoint comment to apply
        // statements one at a time. (PG can run multi-statement strings
        // in a single query call, but explicit per-statement gives us
        // better error reporting.)
        const statements = rawSql
          .split(/-->\s*statement-breakpoint/)
          .map((s) => s.trim())
          .filter((s) => s.length > 0);
        await client.query("BEGIN");
        try {
          for (const stmt of statements) {
            await client.query(stmt);
          }
          await client.query(
            `INSERT INTO drizzle.__drizzle_migrations (hash, created_at) VALUES ($1, $2)`,
            [entry.tag, entry.when],
          );
          await client.query("COMMIT");
          applied.push(entry.tag);
          log(`  applied migration ${entry.tag}`);
        } catch (err) {
          await client.query("ROLLBACK");
          throw err;
        }
      }

      // FTS setup is idempotent (uses IF NOT EXISTS / generated-column
      // pattern); run it once per provisioning so post-migration schema
      // changes that add tsvector columns flow through.
      await client.query(FTS_SETUP_SQL);
    } finally {
      await client.query(`SELECT pg_advisory_unlock($1)`, [
        LOCK_KEY.toString(),
      ]);
    }

    if (applied.length === 0) {
      log(`  migrations at head (${journal.entries.length} total)`);
    }

    // Self-check: journal count vs. applied row count (matches CLAUDE.md
    // runMigrations() contract).
    const finalCount = await client.query<{ c: string }>(
      `SELECT COUNT(*) AS c FROM drizzle.__drizzle_migrations`,
    );
    const dbCount = Number(finalCount.rows[0]?.c ?? "0");
    if (dbCount !== journal.entries.length) {
      throw new Error(
        `Drizzle journal/db mismatch after migration: journal=${journal.entries.length} db=${dbCount}. ` +
          `Diagnose which when value is wrong; do NOT delete rows.`,
      );
    }
  } finally {
    await client.end();
  }
  return applied;
}

async function ensurePublication(
  databaseUrl: string,
  log: (msg: string) => void,
): Promise<boolean> {
  // CREATE PUBLICATION ... FOR ALL TABLES requires superuser. Connect as
  // admin (the OS-level Postgres owner on Homebrew) into the friday DB and
  // create it there. The publication is per-database; querying it from the
  // friday role at runtime is fine — only creation is privileged.
  const adminInFriday = `postgresql://${process.env.USER ?? "postgres"}@localhost:5432/${FRIDAY_DB}`;
  const client = new Client({ connectionString: adminInFriday });
  await client.connect();
  try {
    const exists = await client.query(
      `SELECT 1 FROM pg_publication WHERE pubname = $1`,
      [FRIDAY_PUBLICATION],
    );
    if (exists.rows.length > 0) {
      log(`  publication ${FRIDAY_PUBLICATION} already exists`);
      return false;
    }
    await client.query(`CREATE PUBLICATION ${FRIDAY_PUBLICATION} FOR ALL TABLES`);
    log(`  created publication ${FRIDAY_PUBLICATION} (as admin)`);
    return true;
  } finally {
    await client.end();
  }
}

async function ensureWalLevelLogical(
  log: (msg: string) => void,
): Promise<void> {
  // ALTER SYSTEM requires superuser; use the same admin connection
  // pattern as ensurePublication. `wal_level` is a `postmaster`-level
  // setting — applying it requires a Postgres restart, NOT just
  // `pg_reload_conf()`. We surface that with a clear log message and
  // a non-fatal continuation so first-time setup completes; the
  // operator restarts Postgres and re-runs `friday doctor` to confirm.
  const admin = new Client({ connectionString: adminConnectionUrl() });
  await admin.connect();
  try {
    const cur = await admin.query<{ wal_level: string }>(`SHOW wal_level`);
    const lvl = cur.rows[0]?.wal_level;
    if (lvl === "logical") {
      log(`  wal_level already logical`);
      return;
    }
    // Persist the change so it survives the restart.
    await admin.query(`ALTER SYSTEM SET wal_level = 'logical'`);
    log(`  ALTER SYSTEM SET wal_level = 'logical' (was: ${lvl ?? "unknown"})`);
    log(
      `  ⚠ restart Postgres for the change to take effect: ` +
        `\`brew services restart postgresql@18\` ` +
        `(or your platform's equivalent). Re-run \`friday doctor\` ` +
        `after the restart to confirm.`,
    );
  } finally {
    await admin.end();
  }
}

/* -------------------- read-only health probes -------------------- */
// Exposed for friday doctor.

export interface PgHealth {
  reachable: boolean;
  reachableReason?: string;
  roleExists: boolean;
  databaseExists: boolean;
  migrationsAtHead: boolean;
  migrationsApplied: number;
  migrationsExpected: number;
  publicationExists: boolean;
  zeroAuthSecretPresent: boolean;
  /** Zero requires Postgres `wal_level = logical` for logical replication
   *  (ADR-024). `replica` (the default) leaves Zero in a boot loop with
   *  `Postgres must be configured with "wal_level = logical"`. */
  walLevelLogical: boolean;
  walLevelActual: string | null;
}

export async function probePostgresHealth(opts?: {
  migrationsDir?: string;
}): Promise<PgHealth> {
  const result: PgHealth = {
    reachable: false,
    roleExists: false,
    databaseExists: false,
    migrationsAtHead: false,
    migrationsApplied: 0,
    migrationsExpected: 0,
    publicationExists: false,
    zeroAuthSecretPresent: !!process.env.ZERO_AUTH_SECRET,
    walLevelLogical: false,
    walLevelActual: null,
  };

  try {
    assertPgReady();
    result.reachable = true;
  } catch (err) {
    result.reachableReason = err instanceof Error ? err.message : String(err);
    return result;
  }

  try {
    const admin = new Client({ connectionString: adminConnectionUrl() });
    await admin.connect();
    try {
      const role = await admin.query(
        `SELECT 1 FROM pg_roles WHERE rolname = $1`,
        [FRIDAY_ROLE],
      );
      result.roleExists = role.rows.length > 0;
      const db = await admin.query(
        `SELECT 1 FROM pg_database WHERE datname = $1`,
        [FRIDAY_DB],
      );
      result.databaseExists = db.rows.length > 0;
      // wal_level is a server-wide setting visible to any role.
      const wal = await admin.query<{ wal_level: string }>(
        `SHOW wal_level`,
      );
      const lvl = wal.rows[0]?.wal_level ?? null;
      result.walLevelActual = lvl;
      result.walLevelLogical = lvl === "logical";
    } finally {
      await admin.end();
    }
  } catch {
    // Admin probe failed; leave the role/db/wal_level booleans false.
  }

  const databaseUrl = process.env.DATABASE_URL;
  if (databaseUrl && result.databaseExists) {
    try {
      const c = new Client({ connectionString: databaseUrl });
      await c.connect();
      try {
        const pub = await c.query(
          `SELECT 1 FROM pg_publication WHERE pubname = $1`,
          [FRIDAY_PUBLICATION],
        );
        result.publicationExists = pub.rows.length > 0;

        const journalPath = join(
          opts?.migrationsDir ?? defaultMigrationsDir(),
          "meta",
          "_journal.json",
        );
        if (existsSync(journalPath)) {
          const journal = JSON.parse(
            readFileSync(journalPath, "utf8"),
          ) as Journal;
          result.migrationsExpected = journal.entries.length;

          const exists = await c.query<{ c: string }>(
            `SELECT COUNT(*) AS c
               FROM information_schema.tables
              WHERE table_schema = 'drizzle'
                AND table_name = '__drizzle_migrations'`,
          );
          if (Number(exists.rows[0]?.c ?? "0") > 0) {
            const applied = await c.query<{ c: string }>(
              `SELECT COUNT(*) AS c FROM drizzle.__drizzle_migrations`,
            );
            result.migrationsApplied = Number(applied.rows[0]?.c ?? "0");
            result.migrationsAtHead =
              result.migrationsApplied === result.migrationsExpected;
          }
        }
      } finally {
        await c.end();
      }
    } catch {
      // Connection to friday db failed — leave migration/publication false.
    }
  }

  return result;
}

/** Used by tests / tooling that wants a clean drop. NOT exposed to setup. */
export async function dropFridayDatabaseForTest(): Promise<void> {
  const admin = new Client({ connectionString: adminConnectionUrl() });
  await admin.connect();
  try {
    await admin.query(`DROP DATABASE IF EXISTS ${FRIDAY_DB}`);
    await admin.query(`DROP ROLE IF EXISTS ${FRIDAY_ROLE}`);
  } finally {
    await admin.end();
  }
}

/** Read-only helpers used by friday doctor. */
export const FRIDAY_PG_CONSTANTS = {
  FRIDAY_DB,
  FRIDAY_ROLE,
  FRIDAY_PUBLICATION,
} as const;

